In [1]:
%matplotlib inline
# load and show an image with Pillow
from PIL import Image
# load the image
from IPython.display import display # to display images
from matplotlib import pyplot as plt # to display images
from matplotlib.pyplot import figure
import numpy as np


In [2]:
x1 = np.arange(1,5).reshape((2, 2))
x2 = np.arange(5,9).reshape((2, 2))
display('x1',x1)
display('x2',x2)
#Matrix Multiplication
print('Matrix Multiplication (np.matmul) result:\n',np.matmul(x1, x2))

#Element-Wise Matrix Multiplication
print('Element-Wise Matrix Multiplication (np.multiply) result:\n',np.multiply(x1, x2))



'x1'

array([[1, 2],
       [3, 4]])

'x2'

array([[5, 6],
       [7, 8]])

Matrix Multiplication (np.matmul) result:
 [[19 22]
 [43 50]]
Element-Wise Matrix Multiplication (np.multiply) result:
 [[ 5 12]
 [21 32]]


In [3]:
#@title Reminder2: Padding with Zero 
print('Original Matrix\n',x1)
padded = np.zeros(shape=(x1.shape[0]+2,x1.shape[0]+2))
padded[1:3,1:3]=x1
print('Padded Matrix\n',padded)


Original Matrix
 [[1 2]
 [3 4]]
Padded Matrix
 [[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#@title Load Image
fileName = "mix8.png" #@param {type:"string"}
image = Image.open(fileName)
# summarize some details about the image
print('image.format: ', image.format)
print('image mode: ', image.mode)
print('Image size: ',image.size)
imageMatrix=np.array(image)
print('Image shape:', imageMatrix.shape)
# show the image
display(image)
